-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

SELECT 
    (SELECT COUNT(*) FROM CAD_10929) AS TOTAL, 
    (SELECT COUNT(*) FROM CAD_10929 WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) = CURDATE()) AS VENCE_HOJE, 
    (SELECT COUNT(*) FROM CAD_10929 WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) < CURDATE()) AS ATRASADAS, 
    (SELECT COUNT(*) FROM CAD_10929 WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) > CURDATE()) AS A_VENCER 
FROM DUAL
