SELECT 
    ATIV.ID, 
    ATIV.DESCR AS ATIVIDADE, 
    USU.DESCR AS RESPONSAVEL,
    PAR.DESCR AS PARCEIRO, 
    TIPO_PB.DESCR AS PLAYBOOK, 
    DATE_FORMAT(ATIV.PREVISAO_CONCLUSAO, '%d/%m/%Y') AS DATA_PREVISAO, 
    CAT.DESCR AS CATEGORIA, 
    DATE_FORMAT(ATIV.DATA_CRIACAO_ATIVIDADES, '%d/%m/%Y') AS DATA_CRIACAO, 
    ATIV.ANOTACOES_ATIVIDADE AS ANOTACOES, 
    CASE 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL AND ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 'Concluída com atraso' 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL THEN 'Concluída' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE() THEN 'Atrasada' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE() THEN 'Vencem Hoje' 
        ELSE 'A Vencer' 
    END AS STATUS_LABEL, 
    CASE 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL AND ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 'yellow' 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL THEN 'green' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE() THEN 'red' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE() THEN 'yellow' 
        ELSE 'blue' 
    END AS STATUS_COLOR 
FROM CAD_ATIVIDADES ATIV 
LEFT JOIN CAD_PARCEIRO PAR ON PAR.ID = ATIV.ID_CLIENTE 
LEFT JOIN CAD_1039 USU ON USU.ID = ATIV.ID_RESPONSAVEL 
LEFT JOIN CAD_CATEGORIAS CAT ON CAT.ID = ATIV.ID_CATEGORIA_1 
LEFT JOIN CAD_PLAYBOOKS PB ON PB.ID = ATIV.ID_PLAYBOOKS 
LEFT JOIN CAD_TIPOS_DE_PLAYBOOK TIPO_PB ON TIPO_PB.ID = PB.ID_TIPO_DE_PLAYBOOK 
WHERE 
    (:VAR_SEARCH IS NULL OR :VAR_SEARCH = '' OR UPPER(ATIV.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%') OR UPPER(PAR.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%') OR UPPER(USU.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%'))
    AND (
        IFNULL(:VAR_ATIV_FILTRO_SELECIONADO, 'Todos') = 'Todos'
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'Vencem Hoje' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE())
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'Atrasadas' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE())
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'A Vencer' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) > CURDATE())
    )
ORDER BY ATIV.DATA_CRIACAO_ATIVIDADES DESC
