WITH SNAPSHOT AS (
    SELECT MAX(C2.ID_CALENDARIO) AS ID_CALENDARIO
    FROM CC_1325 C2
    WHERE (C2.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (C2.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
),

BASE_CONSOLIDADA AS (
    SELECT
        C.ID_PARCEIRO AS ID,
        PAR.ID_SEGMENTACAO_ATUAL AS SEGMENTO,
        SUM(COALESCE(H.MRR_SK_ATIVO_HIST, 0)) AS MRR_TOTAL
    FROM CC_1325 C
    INNER JOIN SNAPSHOT S
        ON S.ID_CALENDARIO = C.ID_CALENDARIO
    INNER JOIN CAD_1006 PAR
        ON PAR.ID = C.ID_PARCEIRO
    LEFT JOIN CC_MRR_SK_ATIVO_HIST H
        ON H.ID_PARCEIRO = C.ID_PARCEIRO
       AND H.ID_CALENDARIO = C.ID_CALENDARIO
    WHERE C.ID_STATUS_CLIENTE <> 6
      AND (C.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    GROUP BY C.ID_PARCEIRO, PAR.ID_SEGMENTACAO_ATUAL
)

SELECT
    'MRR Total' AS COL0,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'ENT' THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL1,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'PRE' THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL2,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'ADV' THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL3,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'GRO' THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL4,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'DIG' THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL5,
    CONCAT('R$ ', FORMAT(SUM(CASE WHEN SEGMENTO = 'NC'  THEN MRR_TOTAL END), 2, 'pt_BR')) AS COL6,
    CONCAT('R$ ', FORMAT(SUM(MRR_TOTAL), 2, 'pt_BR')) AS COL7
FROM BASE_CONSOLIDADA

UNION ALL

SELECT
    'Total de Parceiros',
    COUNT(CASE WHEN SEGMENTO = 'ENT' THEN ID END),
    COUNT(CASE WHEN SEGMENTO = 'PRE' THEN ID END),
    COUNT(CASE WHEN SEGMENTO = 'ADV' THEN ID END),
    COUNT(CASE WHEN SEGMENTO = 'GRO' THEN ID END),
    COUNT(CASE WHEN SEGMENTO = 'DIG' THEN ID END),
    COUNT(CASE WHEN SEGMENTO = 'NC'  THEN ID END),
    COUNT(*)
FROM BASE_CONSOLIDADA

UNION ALL

SELECT
    'Tkt Medio',
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'ENT' THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'PRE' THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'ADV' THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'GRO' THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'DIG' THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(CASE WHEN SEGMENTO = 'NC'  THEN MRR_TOTAL END), 2, 'pt_BR')),
    CONCAT('R$ ', FORMAT(AVG(MRR_TOTAL), 2, 'pt_BR'))
FROM BASE_CONSOLIDADA;
