SELECT
    'ACOMPANHAMENTO INICAL (AI)' AS TITULO,
    'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES
        WHERE ID_PLAYBOOKS = 4
          AND DATA_CONCLUSAO IS NOT NULL
    ) AS REALIZADO,
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES
        WHERE ID_PLAYBOOKS = 4
    ) AS PREVISTO
FROM DUAL
