SELECT
    CONCAT(ROUND((REALIZADO_TOTAL / PREVISTO_TOTAL) * 100, 1), '%') AS PERCENTUAL,
    CASE
        WHEN ROUND((REALIZADO_TOTAL / PREVISTO_TOTAL) * 100, 1) < 50 THEN '#f8c7bf'
        WHEN ROUND((REALIZADO_TOTAL / PREVISTO_TOTAL) * 100, 1) < 90 THEN '#f8ecbb'
        ELSE '#b6edb6'
    END AS COR
FROM (
    SELECT
        -- REALIZADO TOTAL
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 1 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB1) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 8 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB8) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 6 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB6) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 4 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB4) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 3 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB3) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 7 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB7) +
        (SELECT COUNT(*) FROM (SELECT PB.ID FROM CAD_PLAYBOOKS PB JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS WHERE PB.ID_TIPO_DE_PLAYBOOK = 2 GROUP BY PB.ID HAVING SUM(CASE WHEN ATIV.DATA_CONCLUSAO IS NULL OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1 ELSE 0 END) = 0) AS PB2) +
        (SELECT COUNT(*) FROM CAD_10929 WHERE ID_PLAYBOOKS IN (5, -999) AND DATA_CONCLUSAO IS NOT NULL) +
        (SELECT COUNT(*) FROM CC_1643 WHERE CG_DT_APROVACAO_ IS NOT NULL AND (ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))) +
        (SELECT COUNT(DISTINCT t1.ID_PARCEIRO_CHAVE_LICENCA) FROM CAD_11048 t1 INNER JOIN CAD_11062 t2 ON t1.ID = t2.ID_HISTORICO_AE INNER JOIN CAD_CALENDARIO cal ON cal.ID = DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m%d') LEFT JOIN CC_1325 t3 ON t3.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND t3.ID_CALENDARIO = (SELECT MAX(s.ID_CALENDARIO) FROM CC_1325 s WHERE s.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND LEFT(CAST(s.ID_CALENDARIO AS CHAR), 6) IN (DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m'), DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO - INTERVAL 1 MONTH, '%Y%m'))) WHERE t2.ID_TIPO_DE_ACOMPANHAMENTO = 1 AND t2.DESCRICAO_PLANO_DE_ACAO_CONCLUIDO = 'Sim' AND t2.DT_CONCLUSAO_PLANO_DE_ACAO IS NOT NULL AND (cal.ID IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (t3.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))) +
        (SELECT COUNT(DISTINCT t1.ID_PARCEIRO_CHAVE_LICENCA) FROM CAD_11048 t1 INNER JOIN CAD_11062 t2 ON t1.ID = t2.ID_HISTORICO_AE INNER JOIN CAD_CALENDARIO cal ON cal.ID = DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m%d') LEFT JOIN CC_1325 t3 ON t3.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND t3.ID_CALENDARIO = (SELECT MAX(s.ID_CALENDARIO) FROM CC_1325 s WHERE s.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND LEFT(CAST(s.ID_CALENDARIO AS CHAR), 6) IN (DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m'), DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO - INTERVAL 1 MONTH, '%Y%m'))) WHERE t2.ID_TIPO_DE_ACOMPANHAMENTO = 2 AND t2.DESCRICAO_PLANO_DE_ACAO_CONCLUIDO = 'Sim' AND t2.DT_CONCLUSAO_PLANO_DE_ACAO IS NOT NULL AND (cal.ID IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (t3.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE)))
        AS REALIZADO_TOTAL,

        -- PREVISTO TOTAL
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 1) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 8) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 6) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 4) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 3) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 7) +
        (SELECT COUNT(ID) FROM CAD_PLAYBOOKS WHERE ID_TIPO_DE_PLAYBOOK = 2) +
        (SELECT COUNT(*) FROM CAD_10929 WHERE ID_PLAYBOOKS IN (5, -999)) +
        (SELECT SUM(cal.METAS_CS__META_UNIDADE) FROM CC_1512 cal INNER JOIN CAD_10931 cad ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS WHERE cad.ID_METAS_CS = 8 AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))) +
        (SELECT COUNT(DISTINCT t1.ID_PARCEIRO_CHAVE_LICENCA) FROM CAD_11048 t1 INNER JOIN CAD_11062 t2 ON t1.ID = t2.ID_HISTORICO_AE INNER JOIN CAD_CALENDARIO cal ON cal.ID = DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m%d') LEFT JOIN CC_1325 t3 ON t3.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND t3.ID_CALENDARIO = (SELECT MAX(s.ID_CALENDARIO) FROM CC_1325 s WHERE s.ID_PARCEIRO = t1.ID_PARCEIRO_CHAVE_LICENCA AND LEFT(CAST(s.ID_CALENDARIO AS CHAR), 6) IN (DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO, '%Y%m'), DATE_FORMAT(t2.DT_CONCLUSAO_PLANO_DE_ACAO - INTERVAL 1 MONTH, '%Y%m'))) WHERE t2.ID_TIPO_DE_ACOMPANHAMENTO = 1 AND (cal.ID IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (t3.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))) +
        (SELECT SUM(cal2.METAS_CS__META_UNIDADE) FROM CC_1512 cal2 INNER JOIN CAD_10931 cad ON cad.ID = cal2.ID_METAS_CS__GERENCIAMENTO_DE_METAS WHERE cad.ID_METAS_CS = 1 AND (cal2.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO)) AND (cal2.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE)))
        AS PREVISTO_TOTAL
    FROM DUAL
) AS TOTAIS