SELECT
    'OUTRAS ATIVIDADES' AS TITULO,
    'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
    (
        SELECT COUNT(*)
        FROM CAD_10929
        WHERE ID_PLAYBOOKS IN (5, -999)
          AND DATA_CONCLUSAO IS NOT NULL
    ) AS REALIZADO,
    (
        SELECT COUNT(*)
        FROM CAD_10929
        WHERE ID_PLAYBOOKS IN (5, -999)
    ) AS PREVISTO
FROM DUAL