SELECT
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES ATIV
        JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
        WHERE (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
          AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
          AND (PAR.ID_CONSULTOR_CS IN (:ID_CONSULTOR_CS) OR 'Todos' IN (:ID_CONSULTOR_CS))
    ) AS TOTAL,
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES ATIV
        JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
        WHERE ATIV.DATA_CONCLUSAO IS NULL
          AND DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE()
          AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
          AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
          AND (PAR.ID_CONSULTOR_CS IN (:ID_CONSULTOR_CS) OR 'Todos' IN (:ID_CONSULTOR_CS))
    ) AS VENCE_HOJE,
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES ATIV
        JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
        WHERE ATIV.DATA_CONCLUSAO IS NULL
          AND DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE()
          AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
          AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
          AND (PAR.ID_CONSULTOR_CS IN (:ID_CONSULTOR_CS) OR 'Todos' IN (:ID_CONSULTOR_CS))
    ) AS ATRASADAS,
    (
        SELECT COUNT(*)
        FROM CAD_ATIVIDADES ATIV
        JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
        WHERE ATIV.DATA_CONCLUSAO IS NULL
          AND DATE(ATIV.PREVISAO_CONCLUSAO) > CURDATE()
          AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
          AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
          AND (PAR.ID_CONSULTOR_CS IN (:ID_CONSULTOR_CS) OR 'Todos' IN (:ID_CONSULTOR_CS))
    ) AS A_VENCER
FROM DUAL