SELECT 
    (SELECT COUNT(*) FROM CAD_ATIVIDADES) AS TOTAL, 
    (SELECT COUNT(*) FROM CAD_ATIVIDADES WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) = CURDATE()) AS VENCE_HOJE, 
    (SELECT COUNT(*) FROM CAD_ATIVIDADES WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) < CURDATE()) AS ATRASADAS, 
    (SELECT COUNT(*) FROM CAD_ATIVIDADES WHERE DATA_CONCLUSAO IS NULL AND DATE(PREVISAO_CONCLUSAO) > CURDATE()) AS A_VENCER 
FROM DUAL
