-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

WITH TOTAL AS (
  SELECT COUNT(*) AS TOTAL
  FROM CAD_10929 ATIV
  JOIN CAD_1006 PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
    AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    AND (ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
),

VENCE_HOJE AS (
  SELECT COUNT(*) AS VENCE_HOJE
  FROM CAD_10929 ATIV
  JOIN CAD_1006 PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE ATIV.DATA_CONCLUSAO IS NULL
    AND DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE()
    AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
    AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    AND (ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
),

ATRASADAS AS (
  SELECT COUNT(*) AS ATRASADAS
  FROM CAD_10929 ATIV
  JOIN CAD_1006 PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE ATIV.DATA_CONCLUSAO IS NULL
    AND DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE()
    AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
    AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    AND (ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
),

A_VENCER AS (
  SELECT COUNT(*) AS A_VENCER
  FROM CAD_10929 ATIV
  JOIN CAD_1006 PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE ATIV.DATA_CONCLUSAO IS NULL
    AND DATE(ATIV.PREVISAO_CONCLUSAO) > CURDATE()
    AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
    AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    AND (ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
)

SELECT
  (SELECT TOTAL FROM TOTAL) AS TOTAL,
  (SELECT VENCE_HOJE FROM VENCE_HOJE) AS VENCE_HOJE,
  (SELECT ATRASADAS FROM ATRASADAS) AS ATRASADAS,
  (SELECT A_VENCER FROM A_VENCER) AS A_VENCER
FROM DUAL;
