-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

SELECT 
    ATIV.ID, 
    ATIV.DESCR AS ATIVIDADE, 
    USU.DESCR AS RESPONSAVEL,
    PAR.DESCR AS PARCEIRO, 
    TIPO_PB.DESCR AS PLAYBOOK,  
    DATE_FORMAT(ATIV.DATA_CRIACAO_ATIVIDADES, '%d/%m/%Y') AS DATA_CRIACAO,
    DATE_FORMAT(ATIV.PREVISAO_CONCLUSAO, '%d/%m/%Y') AS DATA_PREVISAO,
    ATIV.ANOTACOES_ATIVIDADE AS ANOTACOES,
    ATIV.ANEXO,
    CASE 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL AND ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 'Concluída com atraso' 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL THEN 'Concluída' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE() THEN 'Atrasada' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE() THEN 'Vencem Hoje' 
        ELSE 'A Vencer' 
    END AS STATUS_LABEL, 
    CASE 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL AND ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 'yellow' 
        WHEN ATIV.DATA_CONCLUSAO IS NOT NULL THEN 'green' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE() THEN 'red' 
        WHEN DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE() THEN 'yellow' 
        ELSE 'blue' 
    END AS STATUS_COLOR 
FROM CAD_10929 ATIV 
LEFT JOIN CAD_1006 PAR ON PAR.ID = ATIV.ID_CLIENTE 
LEFT JOIN CAD_1039 USU ON USU.ID = ATIV.ID_RESPONSAVEL 
LEFT JOIN CAD_CATEGORIAS CAT ON CAT.ID = ATIV.ID_CATEGORIA_1 
LEFT JOIN CAD_10967 PB ON PB.ID = ATIV.ID_PLAYBOOKS 
LEFT JOIN CAD_TIPOS_DE_PLAYBOOK TIPO_PB ON TIPO_PB.ID = PB.ID_TIPO_DE_PLAYBOOK 
LEFT JOIN CAD_TEMPLATE_ATIVIDADES TPL ON TPL.ID_TIPOS_DE_PLAYBOOK = PB.ID_TIPO_DE_PLAYBOOK AND TPL.ID_TIPOS_DE_ATIVIDADE = ATIV.ID_TIPO_DA_ATIVIDADE 
WHERE 
    (:VAR_SEARCH IS NULL OR :VAR_SEARCH = '' OR UPPER(ATIV.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%') OR UPPER(PAR.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%') OR UPPER(USU.DESCR) LIKE CONCAT('%', UPPER(:VAR_SEARCH), '%'))
    AND (
        IFNULL(:VAR_ATIV_FILTRO_SELECIONADO, 'Todos') = 'Todos'
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'Vencem Hoje' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) = CURDATE())
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'Atrasadas' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) < CURDATE())
        OR (:VAR_ATIV_FILTRO_SELECIONADO = 'A Vencer' AND ATIV.DATA_CONCLUSAO IS NULL AND DATE(ATIV.PREVISAO_CONCLUSAO) > CURDATE())
    )
    AND (DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
    AND (PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
    AND (ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
ORDER BY ATIV.DATA_CRIACAO_ATIVIDADES DESC, TPL.ORDEM_ATIVIDADE;