-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

-- [ATIV] Salvar playbook

INSERT INTO CAD_10967 (
    ID_CLIENTE_1, 
    ID_USUARIO, 
    ID_TIPO_DE_PLAYBOOK, 
    DATA_CRIACAO_PLAYBOOKS, 
    USUARIO_CRIACAO_PLAYBOOKS
) VALUES (
    :VAR_ATIV_PB_CLIENTE, 
    :VAR_ATIV_PB_RESPONSAVEL, 
    :VAR_ATIV_PB_TIPO, 
    NOW(), 
    :VAR_USER
);
