-- [ATIV] Adicionar atividade

INSERT INTO CAD_ATIVIDADES (
  ID,
  DESCR,
  DATA_INICIO,
  PREVISAO_CONCLUSAO,
  DATA_CONCLUSAO,
  HORAS_TOTAIS,
  ANOTACOES_ATIVIDADE,
  USUARIO_CRIACAO_ATIVIDADES,
  DATA_CRIACAO_ATIVIDADES,
  FOTO_CRIACAO_ATIVIDADES,
  DATA_ULT_ALTERACAO_ATIVIDADES,
  USUARIO_ULT_ALTERACAO_ATIVIDADES,
  FOTO_ULT_ALTERACAO_ATIVIDADES
) 
SELECT
  (SELECT COALESCE(MAX(ID), 0) + 1 FROM CAD_ATIVIDADES),
  :VAR_ATIV_TITULO,
  NULLIF(:VAR_ATIV_DT_INICIO, ''),
  NULLIF(:VAR_ATIV_DT_PREV_CON, ''),
  NULLIF(:VAR_ATIV_DT_CONCLUSAO, ''),
  NULLIF(:VAR_ATIV_HORAS, ''),
  NULLIF(:VAR_ATIV_ANOTACOES, ''),
  :VAR_USER,
  NOW(),
  NULL,
  NOW(),
  :VAR_USER,
  NULL