-- [ATIV] Salvar playbook

INSERT INTO CAD_PLAYBOOKS (
    ID_CLIENTE_1, 
    ID_USUARIO, 
    ID_TIPO_DE_PLAYBOOK, 
    DATA_CRIACAO_PLAYBOOKS, 
    USUARIO_CRIACAO_PLAYBOOKS
) VALUES (
    :VAR_ATIV_PB_CLIENTE, 
    :VAR_ATIV_PB_RESPONSAVEL, 
    :VAR_ATIV_PB_TIPO, 
    NOW(), 
    :VAR_USER
);
