-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

-- [ATIV] Salvar atividades do playbook

INSERT INTO CAD_10929 (
    ID,
    ID_PLAYBOOKS,
    ID_CLIENTE,
    ID_RESPONSAVEL,
    DESCR,
    ID_TIPO_DA_ATIVIDADE,
    PREVISAO_CONCLUSAO,
    ID_CATEGORIA_1,
    DATA_CRIACAO_ATIVIDADES,
    USUARIO_CRIACAO_ATIVIDADES,
    DATA_ULT_ALTERACAO_ATIVIDADES,
    USUARIO_ULT_ALTERACAO_ATIVIDADES,
    FOTO_CRIACAO_ATIVIDADES,
    FOTO_ULT_ALTERACAO_ATIVIDADES,
    DATA_INICIO
) 
SELECT 
    (SELECT COALESCE(MAX(ID), 0) FROM CAD_10929) + ROW_NUMBER() OVER (ORDER BY TPL.ID),
    PB.ID, 
    PB.ID_CLIENTE_1, 
    PB.ID_RESPONSAVEL_1, 
    TPL.DESCR, 
    TPL.ID_TIPOS_DE_ATIVIDADE, 
    DATE_ADD(CURDATE(), INTERVAL COALESCE(TPL.PRAZO_DIAS, 0) DAY),
    1,
    NOW(), 
    :VAR_USER,
    NOW(),
    :VAR_USER,
    NULL,
    NULL,
    CURDATE()
FROM CAD_TEMPLATE_ATIVIDADES TPL 
    JOIN CAD_10967 PB 
        ON PB.ID_TIPO_DE_PLAYBOOK = TPL.ID_TIPOS_DE_PLAYBOOK 
WHERE PB.ID = :VAR_ATIV_NOVO_ID_PB
