-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

-- [ATIV] Concluir atividade

UPDATE CAD_10929
SET DATA_CONCLUSAO = CURDATE()
WHERE ID = :VAR_ATIV_ID_SELECIONADO
    AND CHAR_LENGTH(ANOTACOES_ATIVIDADE) >= 20
