-- COLUNAS
-- CAD_1 = Calendário
-- CAD_1006 = Parceiro
-- CAD_1007 = Unidade
-- CAD_10931 = Gerenciamento de Metas
-- CC_1512 = Metas CS
-- CC_1643 = Clube de Gestão
-- CC_1039 = Usuários

WITH REALIZADO AS (
    SELECT
        COUNT(*) AS REALIZADO
    FROM CC_1643 c
    INNER JOIN CAD_1 cal
        ON cal.ID = DATE_FORMAT(c.CG_DT_APROVACAO_, '%Y%m%d')
    INNER JOIN CAD_1007 un
        ON un.ID = c.ID_UNIDADE
    INNER JOIN CAD_1039 u
        ON u.ID = c.ID_USUARIO
    WHERE c.CG_DT_APROVACAO_ IS NOT NULL
      AND (cal.ID IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (un.ID IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
      AND (un.ID_CS_MATRIZ IN (:ID_CS_MATRIZ) OR 'Todos' IN (:ID_CS_MATRIZ))
      AND (u.ID IN (:ID_USUARIO) OR 'Todos' IN (:ID_USUARIO))
),

PREVISTO_BASE AS (
    SELECT
        SUM(cal.METAS_CS__META_UNIDADE) AS META_AE
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 8
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
      AND 'Todos' IN (:ID_USUARIO)

    UNION ALL

    SELECT
        SUM(cal.METAS_CS__META_INDIVIDUAL) AS META_AE
    FROM CC_1513 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    INNER JOIN CAD_1039 u
        ON u.ID = cal.ID_USUARIO
    WHERE cad.ID_METAS_CS = 8
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
      AND u.ID IN (:ID_USUARIO)
      AND 'Todos' NOT IN (:ID_USUARIO)
),

PREVISTO AS (
    SELECT
        COALESCE(SUM(META_AE), 0) AS PREVISTO
    FROM PREVISTO_BASE
),

ATINGIMENTO AS (
    SELECT
        ROUND(
            CASE
                WHEN COALESCE(r.REALIZADO, 0) = 0
                 AND COALESCE(p.PREVISTO, 0) = 0
                    THEN 100
                ELSE
                    CAST(COALESCE(r.REALIZADO, 0) AS DECIMAL(18, 4))
                    / NULLIF(CAST(p.PREVISTO AS DECIMAL(18, 4)), 0) * 100
            END,
            2
        ) AS ATINGIMENTO
    FROM REALIZADO r
    CROSS JOIN PREVISTO p
)

SELECT
    p.PREVISTO AS PREVISTO,
    r.REALIZADO AS REALIZADO,
    a.ATINGIMENTO AS ATINGIMENTO
FROM REALIZADO r
CROSS JOIN PREVISTO p
CROSS JOIN ATINGIMENTO a;
