WITH REALIZADO AS (
    SELECT COUNT(*) AS REALIZADO
    FROM CC_1643 C
    INNER JOIN CAD_CALENDARIO cal
        ON cal.ID = DATE_FORMAT(C.CG_DT_APROVACAO_, '%Y%m%d')
    INNER JOIN CAD_1007 u
        ON u.ID = C.ID_UNIDADE
    WHERE C.CG_DT_APROVACAO_ IS NOT NULL
      AND (cal.ID IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (u.ID IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
      AND (u.ID_CS_MATRIZ IN (:ID_CS_MATRIZ) OR 'Todos' IN (:ID_CS_MATRIZ))
),
PREVISTO AS (
    SELECT SUM(cal.METAS_CS__META_UNIDADE) AS META_AE
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 8
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
),
ATINGIMENTO AS (
    SELECT ROUND(
        (
            SELECT COUNT(DISTINCT ID_PARCEIRO)
            FROM CC_1642
        )
        /
        (
            SELECT SUM(cal.METAS_CS__META_UNIDADE)
            FROM CC_1512 cal
            INNER JOIN CAD_10931 cad
                ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
            WHERE cad.ID_METAS_CS = 8
              AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
              AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
        )
        * 100,
        0
    ) AS PERCENTUAL
    FROM DUAL
)
SELECT
    r.REALIZADO AS CLUBE_GESTAO_REALIZADO,
    p.META_AE AS CLUBE_GESTAO_PREVISTO,
    a.PERCENTUAL AS CLUBE_GESTAO_PERCENTUAL
FROM REALIZADO r
CROSS JOIN PREVISTO p
CROSS JOIN ATINGIMENTO a;
