WITH REALIZADO_BASE AS (
    SELECT
        SUM(A.PERDAS) AS PERDAS,
        SUM(A.BASE_MRR) AS BASE_MRR,
        (SUM(A.PERDAS) / NULLIF(SUM(A.BASE_MRR), 0)) * 100 AS MRR_CHURN
    FROM (
        SELECT
            SUM(PER.VLR_PERDA_MRR_CHURN) AS PERDAS,
            0 AS BASE_MRR,
            PER.ID_CALENDARIO
        FROM CC_1671 PER
        WHERE PER.ID_TIPO_DE_PERDA = 'DEFINITIVO '
          AND (PER.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
          AND (PER.ID_PARCEIRO IN (:ID_PARCEIRO) OR 'Todos' IN (:ID_PARCEIRO))
          AND (
              EXISTS (
                  SELECT 1
                  FROM CC_1609
                  WHERE ID_PARCEIRO = PER.ID_PARCEIRO
                    AND ID_USUARIOS = :ID_USUARIOS
              )
              OR 'Todos' IN (:ID_USUARIOS)
          )
        GROUP BY PER.ID_CALENDARIO

        UNION ALL

        SELECT
            0 AS PERDAS,
            SUM(MRR.MRR_HISTORICO) AS BASE_MRR,
            MRR.ID_CALENDARIO
        FROM CC_1333 MRR
        WHERE (
                  CASE
                      WHEN MOD(MRR.ID_CALENDARIO, 10000) = 101
                          THEN (MRR.ID_CALENDARIO - 10000) + 1100
                      ELSE MRR.ID_CALENDARIO - 100
                  END IN (:ID_CALENDARIO)
                  OR 'Todos' IN (:ID_CALENDARIO)
              )
          AND (MRR.ID_PARCEIRO IN (:ID_PARCEIRO) OR 'Todos' IN (:ID_PARCEIRO))
          AND (
              EXISTS (
                  SELECT 1
                  FROM CC_1609
                  WHERE ID_PARCEIRO = MRR.ID_PARCEIRO
                    AND ID_USUARIOS = :ID_USUARIOS
              )
              OR 'Todos' IN (:ID_USUARIOS)
          )
        GROUP BY MRR.ID_CALENDARIO
    ) A
),
REALIZADO_FINAL AS (
    SELECT
        CONCAT(
            SUBSTR(
                CAST(ROUND(CAST(AVG(MRR_CHURN) AS DECIMAL(10,2)), 2) + 100 AS CHAR(10)),
                3
            ),
            '&#37;'
        ) AS MRR_CHURN
    FROM REALIZADO_BASE
),
PREVISTO_ULTIMO_MES AS (
    SELECT MAX(cal.ID_CALENDARIO) AS ID_CALENDARIO_FINAL
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 3
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
),
PREVISTO_META_UNIDADE AS (
    SELECT AVG(cal.METAS_CS__META_UNIDADE) AS VALOR_META
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    INNER JOIN PREVISTO_ULTIMO_MES um
        ON um.ID_CALENDARIO_FINAL = cal.ID_CALENDARIO
    WHERE cad.ID_METAS_CS = 3
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
),
PREVISTO_REGRA_FIXA AS (
    SELECT
        CASE
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2026' THEN 0.7
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2025' THEN 0.8
            ELSE 1
        END AS VALOR_META
    FROM PREVISTO_ULTIMO_MES um
),
PREVISTO_RESULTADO AS (
    SELECT
        CASE
            WHEN 'Todos' IN (:ID_UNIDADE) THEN rf.VALOR_META
            ELSE mu.VALOR_META
        END AS VALOR_FINAL
    FROM PREVISTO_REGRA_FIXA rf
    CROSS JOIN PREVISTO_META_UNIDADE mu
),
PREVISTO_FINAL AS (
    SELECT
        CONCAT(
            SUBSTR(
                CAST(ROUND(CAST(VALOR_FINAL AS DECIMAL(10,2)), 2) + 100 AS CHAR(10)),
                3
            ),
            '%'
        ) AS MRR_CHURN_RESULTADO
    FROM PREVISTO_RESULTADO
),
ATING_BASE_FILTRADA AS (
    SELECT
        cal.ID_CALENDARIO,
        cal.ID_UNIDADE,
        cal.METAS_CS__META_UNIDADE AS VALOR_META
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 3
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
),
ATING_ULTIMO_MES AS (
    SELECT MAX(ID_CALENDARIO) AS ID_CALENDARIO_FINAL
    FROM CC_1512
    WHERE (ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
),
ATING_META_REAL AS (
    SELECT AVG(bf.VALOR_META) AS VALOR_META
    FROM ATING_BASE_FILTRADA bf
    INNER JOIN ATING_ULTIMO_MES um
        ON um.ID_CALENDARIO_FINAL = bf.ID_CALENDARIO
),
ATING_REGRA_FIXA AS (
    SELECT
        CASE
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2026' THEN 0.7
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2025' THEN 0.8
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2024' THEN 1
        END AS VALOR_META
    FROM ATING_ULTIMO_MES um
),
ATING_PREVISTO AS (
    SELECT
        CASE
            WHEN 'Todos' IN (:ID_UNIDADE) THEN rf.VALOR_META
            ELSE COALESCE(mr.VALOR_META, rf.VALOR_META)
        END AS PREVISTO
    FROM ATING_REGRA_FIXA rf
    CROSS JOIN ATING_META_REAL mr
),
ATING_REALIZADO AS (
    SELECT
        (SUM(A.PERDAS) / NULLIF(SUM(A.BASE_MRR), 0)) * 100 AS REALIZADO
    FROM (
        SELECT
            SUM(PER.PERDAS_MRR) * -1 AS PERDAS,
            0 AS BASE_MRR
        FROM CC_1104 PER
        WHERE PER.ID_TIPO_DE_PERDA = 'DEFINITIVO '
          AND (PER.ID_CALENDARIO IN (:ID_CALENDARIO) OR CONCAT(:ID_CALENDARIO) = 'Todos')
          AND (PER.ID_PARCEIRO IN (:ID_PARCEIRO) OR CONCAT(:ID_PARCEIRO) = 'Todos')
          AND ID_CATEGORIA_MRR IN (15, 14, 2, 1)
          AND EXISTS (
              SELECT 1
              FROM CC_1609
              WHERE ID_PARCEIRO = PER.ID_PARCEIRO
                AND ID_USUARIOS = :ID_USUARIOS
          )

        UNION ALL

        SELECT
            SUM(CAN.VALOR_DE_CANCELAMENTO) AS PERDAS,
            0 AS BASE_MRR
        FROM CC_1173 CAN
        WHERE CAN.ID_CANCELAMENTO_POR_LIMPEZA_DE_BASE <> 'S'
          AND (CONCAT(LEFT(CAN.ID_CALENDARIO, 6), '01') IN (:ID_CALENDARIO) OR CONCAT(:ID_CALENDARIO) = 'Todos')
          AND (CAN.ID_PARCEIRO IN (:ID_PARCEIRO) OR CONCAT(:ID_PARCEIRO) = 'Todos')
          AND EXISTS (
              SELECT 1
              FROM CC_1609
              WHERE ID_PARCEIRO = CAN.ID_PARCEIRO
                AND ID_USUARIOS = :ID_USUARIOS
          )

        UNION ALL

        SELECT
            0 AS PERDAS,
            SUM(MRR.MRR_HISTORICO) AS BASE_MRR
        FROM CC_1333 MRR
        WHERE (
                  DATE_FORMAT(DATE_ADD(MRR.ID_CALENDARIO, INTERVAL 1 MONTH), '%Y%m%d') IN (:ID_CALENDARIO)
                  OR CONCAT(:ID_CALENDARIO) = 'Todos'
              )
          AND (MRR.ID_PARCEIRO IN (:ID_PARCEIRO) OR CONCAT(:ID_PARCEIRO) = 'Todos')
          AND EXISTS (
              SELECT 1
              FROM CC_1609
              WHERE ID_PARCEIRO = MRR.ID_PARCEIRO
                AND ID_USUARIOS = :ID_USUARIOS
          )
    ) A
),
ATING_RESULTADO AS (
    SELECT (((p.PREVISTO - r.REALIZADO) / NULLIF(p.PREVISTO, 0)) + 1) * 100 AS ATINGIMENTO
    FROM ATING_PREVISTO p
    CROSS JOIN ATING_REALIZADO r
),
ATING_FINAL AS (
    SELECT CONCAT(ROUND(ATINGIMENTO, 2), '%') AS ATINGIMENTO_MRR_CHURN
    FROM ATING_RESULTADO
)
SELECT
    rf.MRR_CHURN AS MRR_CHURN_REALIZADO,
    pf.MRR_CHURN_RESULTADO AS MRR_CHURN_PREVISTO,
    af.ATINGIMENTO_MRR_CHURN AS ATINGIMENTO_MRR_CHURN
FROM REALIZADO_FINAL rf
CROSS JOIN PREVISTO_FINAL pf
CROSS JOIN ATING_FINAL af;
