WITH BASE_FILTRADA AS (
    SELECT
        cal.ID_CALENDARIO,
        cal.ID_UNIDADE,
        cal.METAS_CS__META_UNIDADE AS VALOR_META
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 2
      AND (
          cal.ID_CALENDARIO IN (:ID_CALENDARIO)
          OR 'Todos' IN (:ID_CALENDARIO)
      )
      AND (
          cal.ID_UNIDADE IN (:ID_UNIDADE)
          OR 'Todos' IN (:ID_UNIDADE)
      )
),
ULTIMO_MES AS (
    SELECT MAX(ID_CALENDARIO) AS ID_CALENDARIO_FINAL
    FROM BASE_FILTRADA
),
META_REAL AS (
    SELECT AVG(bf.VALOR_META) AS VALOR_META
    FROM BASE_FILTRADA bf
    INNER JOIN ULTIMO_MES um
        ON um.ID_CALENDARIO_FINAL = bf.ID_CALENDARIO
),
REGRA_FIXA AS (
    SELECT
        CASE
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2026' THEN
                CASE
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '01' AND '03' THEN 40
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '04' AND '06' THEN 42
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '07' AND '09' THEN 44
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '10' AND '12' THEN 48
                END
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2025' THEN
                CASE
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '01' AND '03' THEN 42
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '04' AND '06' THEN 42
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '07' AND '09' THEN 40
                    WHEN SUBSTRING(um.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '10' AND '12' THEN 44
                END
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2024' THEN 30
            WHEN LEFT(um.ID_CALENDARIO_FINAL, 4) = '2023' THEN 25
        END AS VALOR_META
    FROM ULTIMO_MES um
),
NPS_PREVISTO AS (
    SELECT
        CASE
            WHEN 'Todos' IN (:ID_UNIDADE) THEN rf.VALOR_META
            ELSE mr.VALOR_META
        END AS NPS_RESULTADO
    FROM REGRA_FIXA rf
    CROSS JOIN META_REAL mr
),
NPS_REALIZADO AS (
    SELECT
        ROUND(
            (
                SUM(CASE WHEN R.ID_ESCALA_NPS IN (9, 10) THEN 1 ELSE 0 END)
                - SUM(CASE WHEN R.ID_ESCALA_NPS <= 6 THEN 1 ELSE 0 END)
            ) / NULLIF(COUNT(*), 0) * 100.0,
            0
        ) AS NPS
    FROM CC_1424 R
    INNER JOIN CAD_8732 C
        ON C.ID = R.ID_CONTATO_PESQUISA_NPS
    WHERE (
        R.ID_CALENDARIO IN (:ID_CALENDARIO)
        OR 'Todos' IN (:ID_CALENDARIO)
    )
      AND C.ID_PESQUISA_NPS_INVALIDA = 'N'
)
SELECT
    nr.NPS AS NPS,
    np.NPS_RESULTADO AS NPS_RESULTADO,
    ROUND(
        nr.NPS / NULLIF(np.NPS_RESULTADO, 0) * 100.0,
        0
    ) AS PERCENTUAL_NPS
FROM NPS_REALIZADO nr
CROSS JOIN NPS_PREVISTO np;
