WITH ULTIMO_MES_ANO AS (
    SELECT MAX(cal.ID_CALENDARIO) AS ID_CALENDARIO_FINAL
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    WHERE cad.ID_METAS_CS = 2
      AND (cal.ID_CALENDARIO IN (:ID_CALENDARIO) OR 'Todos' IN (:ID_CALENDARIO))
),

FILTRO_UNIDADE AS (
    SELECT COUNT(DISTINCT cal.ID_UNIDADE) AS QTD
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    INNER JOIN CAD_1007 uni
        ON uni.ID = cal.ID_UNIDADE
    WHERE cad.ID_METAS_CS = 2
      AND (cal.ID_UNIDADE IN (:ID_UNIDADE) OR 'Todos' IN (:ID_UNIDADE))
      AND (uni.ID_CS_MATRIZ IN (:ID_CS_MATRIZ) OR 'Todos' IN (:ID_CS_MATRIZ))
),

BASE_FILTRADA AS (
    SELECT
        cal.ID_CALENDARIO,
        cal.ID_UNIDADE,
        cal.METAS_CS__META_UNIDADE AS VALOR_META
    FROM CC_1512 cal
    INNER JOIN CAD_10931 cad
        ON cad.ID = cal.ID_METAS_CS__GERENCIAMENTO_DE_METAS
    INNER JOIN CAD_1007 uni
        ON uni.ID = cal.ID_UNIDADE
    WHERE cad.ID_METAS_CS = 2
      AND (
            cal.ID_CALENDARIO IN (:ID_CALENDARIO)
            OR 'Todos' IN (:ID_CALENDARIO)
          )
      AND (
            cal.ID_UNIDADE IN (:ID_UNIDADE)
            OR 'Todos' IN (:ID_UNIDADE)
          )
      AND (
            uni.ID_CS_MATRIZ IN (:ID_CS_MATRIZ)
            OR 'Todos' IN (:ID_CS_MATRIZ)
          )
),

ULTIMO_MES AS (
    SELECT MAX(ID_CALENDARIO) AS ID_CALENDARIO_FINAL
    FROM BASE_FILTRADA
),

META_REAL AS (
    SELECT AVG(bf.VALOR_META) AS VALOR_META
    FROM BASE_FILTRADA bf
    INNER JOIN ULTIMO_MES um ON um.ID_CALENDARIO_FINAL = bf.ID_CALENDARIO
),

REGRA_FIXA AS (
    SELECT 
        CASE
            WHEN LEFT(uma.ID_CALENDARIO_FINAL, 4) = '2026' THEN 
                CASE 
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '01' AND '03' THEN 40
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '04' AND '06' THEN 42
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '07' AND '09' THEN 44
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '10' AND '12' THEN 48
                END             
            WHEN LEFT(uma.ID_CALENDARIO_FINAL, 4) = '2025' THEN
                CASE
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '01' AND '03' THEN 42
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '04' AND '06' THEN 42
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '07' AND '09' THEN 40
                    WHEN SUBSTRING(uma.ID_CALENDARIO_FINAL, 5, 2) BETWEEN '10' AND '12' THEN 44
                END
            WHEN LEFT(uma.ID_CALENDARIO_FINAL, 4) = '2024' THEN 30
            WHEN LEFT(uma.ID_CALENDARIO_FINAL, 4) = '2023' THEN 25
        END AS VALOR_META
    FROM ULTIMO_MES_ANO uma 
),  

RESULTADO AS (
    SELECT
        CASE
            WHEN fu.QTD = 1 THEN mr.VALOR_META
            ELSE rf.VALOR_META
        END AS NPS_PREVISTO     
    FROM REGRA_FIXA rf
    LEFT JOIN META_REAL mr ON 1=1
    CROSS JOIN FILTRO_UNIDADE fu 
),

NPS_PREVISTO AS (
    SELECT
        CASE
            WHEN fu.QTD = 1 THEN mr.VALOR_META
            ELSE rf.VALOR_META
        END AS NPS_RESULTADO
    FROM REGRA_FIXA rf
    LEFT JOIN META_REAL mr
        ON 1 = 1
    CROSS JOIN FILTRO_UNIDADE fu
),

NPS_REALIZADO AS (
    SELECT
        ROUND(
            (
                SUM(CASE WHEN r.ID_ESCALA_NPS IN (9, 10) THEN 1 ELSE 0 END)
                - SUM(CASE WHEN r.ID_ESCALA_NPS <= 6 THEN 1 ELSE 0 END)
            ) * 100.0 / NULLIF(COUNT(*), 0),
            0
        ) AS NPS
    FROM CC_1424 r
    INNER JOIN CC_1325 t3
        ON t3.ID_PARCEIRO = r.ID_PARCEIRO
       AND t3.ID_CALENDARIO = (
            SELECT MAX(s.ID_CALENDARIO)
            FROM CC_1325 s
            WHERE s.ID_PARCEIRO = r.ID_PARCEIRO
        )
    WHERE (
            r.ID_CALENDARIO IN (:ID_CALENDARIO)
            OR 'Todos' IN (:ID_CALENDARIO)
          )
      AND (
            t3.ID_UNIDADE IN (:ID_UNIDADE)
            OR 'Todos' IN (:ID_UNIDADE)
          )
      AND r.ID_CONTATO_PESQUISA_NPS IN (
            SELECT ID
            FROM CAD_8732
            WHERE ID_PESQUISA_NPS_INVALIDA = 'N'
          )
),

NPS_ATINGIMENTO AS (
    SELECT
        ROUND(
            COALESCE(nr.NPS, 0) / NULLIF(np.NPS_RESULTADO, 0) * 100.0,
            0
        ) AS NPS_ATINGIMENTO
    FROM NPS_REALIZADO nr
    CROSS JOIN NPS_PREVISTO np
)

SELECT
    NPS_PREVISTO.NPS_RESULTADO AS PREVISTO,
    NPS_REALIZADO.NPS AS REALIZADO,
    NPS_ATINGIMENTO.NPS_ATINGIMENTO AS ATINGIMENTO
FROM NPS_PREVISTO
CROSS JOIN NPS_REALIZADO
CROSS JOIN NPS_ATINGIMENTO;
