SELECT
  'CHECK-IN DE EXPERIÊNCIA' AS TITULO,
  'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
  (
    SELECT COUNT(*)
    FROM
      (
        SELECT PB.ID
        FROM CAD_PLAYBOOKS PB
        JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS
        JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
        WHERE
          PB.ID_TIPO_DE_PLAYBOOK = 8 AND (
            DATE_FORMAT (ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO)
            OR 'Todos' IN (:ID_CALENDARIO)
          ) AND (
            PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE)
            OR 'Todos' IN (:ID_UNIDADE)
          )
        GROUP BY PB.ID
        HAVING
          SUM(
            CASE
              WHEN ATIV.DATA_CONCLUSAO IS NULL
              OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO THEN 1
              ELSE 0
            END
          ) = 0
      ) AS PlaybooksConcluidosNoPrazo
  ) AS REALIZADO,
  (
    SELECT COUNT(DISTINCT PB.ID)
    FROM CAD_PLAYBOOKS PB
    JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS
    JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
    WHERE
      PB.ID_TIPO_DE_PLAYBOOK = 8 AND (
        DATE_FORMAT (ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO)
        OR 'Todos' IN (:ID_CALENDARIO)
      ) AND (
        PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE)
        OR 'Todos' IN (:ID_UNIDADE)
      )
  ) AS PREVISTO
FROM DUAL
