-- COLUNAS
-- CAD_10929 = Atividades
-- CAD_10967 = Playbooks
-- CAD_1006 = Parceiro

-- Cálculo de Outras Atividades Concluídas no Prazo (Lógica Corrigida)
WITH ATIVIDADES_FILTRADAS AS (
  SELECT
    ATIV.DATA_CONCLUSAO,
    ATIV.PREVISAO_CONCLUSAO
  FROM CAD_10929 ATIV
  LEFT JOIN CAD_10967 PB ON PB.ID = ATIV.ID_PLAYBOOKS
  JOIN CAD_1006 PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE
    (ATIV.ID_PLAYBOOKS IS NULL OR PB.ID_TIPO_DE_PLAYBOOK = 5)
    AND (
      DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 
      'Todos' IN (:ID_CALENDARIO)
    ) AND (
      PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 
      'Todos' IN (:ID_UNIDADE)
    ) AND (
      ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR
      'Todos' IN (:ID_USUARIO)
    )
)
SELECT
  'OUTRAS ATIVIDADES' AS TITULO,
  'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
  (
    SELECT COUNT(*)
    FROM ATIVIDADES_FILTRADAS
    WHERE DATA_CONCLUSAO IS NOT NULL AND DATA_CONCLUSAO <= PREVISAO_CONCLUSAO
  ) AS REALIZADO,
  (
    SELECT COUNT(*) FROM ATIVIDADES_FILTRADAS
  ) AS PREVISTO;
