-- Cálculo de Outras Atividades Concluídas no Prazo (Lógica Corrigida)
WITH ATIVIDADES_FILTRADAS AS (
  SELECT
    ATIV.DATA_CONCLUSAO,
    ATIV.PREVISAO_CONCLUSAO
  FROM CAD_ATIVIDADES ATIV
  JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE
    (ATIV.ID_PLAYBOOKS = 5 OR ATIV.ID_PLAYBOOKS = -999) -- Condição corrigida para buscar pelo ID do playbook na atividade
    AND (
      DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 
      'Todos' IN (:ID_CALENDARIO)
    ) AND (
      PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 
      'Todos' IN (:ID_UNIDADE)
    ) AND (
      ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR
      'Todos' IN (:ID_USUARIO)
    )
)
SELECT
  'OUTRAS ATIVIDADES' AS TITULO,
  'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
  (
    SELECT COUNT(*)
    FROM ATIVIDADES_FILTRADAS
    WHERE DATA_CONCLUSAO IS NOT NULL AND DATA_CONCLUSAO <= PREVISAO_CONCLUSAO
  ) AS REALIZADO,
  (
    SELECT COUNT(*) FROM ATIVIDADES_FILTRADAS
  ) AS PREVISTO;