-- Cálculo de Passagens de Bastão Concluídas no Prazo
WITH CONCLUIDOS_NO_PRAZO AS (
  SELECT PB.ID
  FROM CAD_PLAYBOOKS PB
  JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS
  JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE PB.ID_TIPO_DE_PLAYBOOK = 1 AND ( -- ID do playbook de Passagem de Bastão
      DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 
      'Todos' IN (:ID_CALENDARIO)
    ) AND (
      PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 
      'Todos' IN (:ID_UNIDADE)
    ) AND (
      ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR
      'Todos' IN (:ID_USUARIO)
    )
  GROUP BY PB.ID
  HAVING SUM(
    CASE
      WHEN ATIV.DATA_CONCLUSAO IS NULL
            OR ATIV.DATA_CONCLUSAO > ATIV.PREVISAO_CONCLUSAO
      THEN 1
      ELSE 0
    END
  ) = 0
),
  
PREVISTO AS (
  SELECT PB.ID
  FROM CAD_PLAYBOOKS PB
  JOIN CAD_ATIVIDADES ATIV ON PB.ID = ATIV.ID_PLAYBOOKS
  JOIN CAD_PARCEIRO PAR ON ATIV.ID_CLIENTE = PAR.ID
  WHERE PB.ID_TIPO_DE_PLAYBOOK = 1 AND ( -- ID do playbook de Passagem de Bastão
      DATE_FORMAT(ATIV.DATA_INICIO, '%Y%m%d') IN (:ID_CALENDARIO) OR 
      'Todos' IN (:ID_CALENDARIO)
    ) AND (
      PAR.ID_UNIDADE_DO_PARCEIRO_ATUAL IN (:ID_UNIDADE) OR 
      'Todos' IN (:ID_UNIDADE)
    ) AND (
      ATIV.ID_RESPONSAVEL IN (:ID_USUARIO) OR
      'Todos' IN (:ID_USUARIO)
    )
  GROUP BY PB.ID
)

SELECT
  'PASSAGEM DE BASTÃO' AS TITULO,
  'CONCLUSÃO NO PRAZO:' AS SUBTITULO,
  (SELECT COUNT(*) FROM CONCLUIDOS_NO_PRAZO) AS REALIZADO,
  (SELECT COUNT(*) FROM PREVISTO) AS PREVISTO;
